In [16]:
import pandas as pd
import numpy as np

sweets = pd.DataFrame({
    "كنافة":np.array([12,14,9,20,23]),
    "بسبوسة":np.array([15,14,23,25,22]),
    "زلابيا":np.array([4,7,10,5,7]),
    "بقلاوة":np.array([10,14,11,22,23]),
    "ام علي":np.array([2,6,8,3,7])
},index=["total ","Day 2","Day 3","Day 4","Day 5"])
sweets

        كنافة  بسبوسة  زلابيا  بقلاوة  ام علي
total      12      15       4      10       2
Day 2      14      14       7      14       6
Day 3       9      23      10      11       8
Day 4      20      25       5      22       3
Day 5      23      22       7      23       7

In [17]:
sum_selas_of_days=pd.DataFrame({"Total":sweets.sum(axis=1)})
sum_selas_of_days

        Total
total      43
Day 2      55
Day 3      61
Day 4      75
Day 5      82

In [18]:
sum_selas_of_tayps=pd.DataFrame({"Total":sweets.sum(axis=0)})
sum_selas_of_tayps

        Total
كنافة      78
بسبوسة     99
زلابيا     33
بقلاوة     80
ام علي     26

In [19]:
max_selas_of_days=pd.DataFrame({"Max":sweets.max(axis=1)})
max_selas_of_days

        Max
total    15
Day 2    14
Day 3    23
Day 4    25
Day 5    23

In [20]:
max_selas_of_typs=pd.DataFrame({"Max":sweets.max(axis=0)})
max_selas_of_typs

        Max
كنافة    23
بسبوسة   25
زلابيا   10
بقلاوة   23
ام علي    8

In [21]:
min_selas_of_days=pd.DataFrame({"Min":sweets.min(axis=1)})
min_selas_of_days

        Min
total     2
Day 2     6
Day 3     8
Day 4     3
Day 5     7

In [22]:
min_selas_of_typs=pd.DataFrame({"Min":sweets.min(axis=0)})
min_selas_of_typs

        Min
كنافة     9
بسبوسة   14
زلابيا    4
بقلاوة   10
ام علي    2

In [23]:
mean_selas_of_days=pd.DataFrame({"Mean":sweets.mean(axis=1)})
mean_selas_of_days

        Mean
total    8.6
Day 2   11.0
Day 3   12.2
Day 4   15.0
Day 5   16.4

In [24]:
mean_selas_of_typs=pd.DataFrame({"Mean":sweets.mean(axis=0)})
mean_selas_of_typs

        Mean
كنافة   15.6
بسبوسة  19.8
زلابيا   6.6
بقلاوة  16.0
ام علي   5.2

In [25]:
pd.DataFrame({"Max":sweets.max()})

        Max
كنافة    23
بسبوسة   25
زلابيا   10
بقلاوة   23
ام علي    8

In [26]:
pd.DataFrame({"Min":sweets.min()})

        Min
كنافة     9
بسبوسة   14
زلابيا    4
بقلاوة   10
ام علي    2

In [27]:
pd.DataFrame({"Mean":sweets.mean()})

        Mean
كنافة   15.6
بسبوسة  19.8
زلابيا   6.6
بقلاوة  16.0
ام علي   5.2

In [28]:
sweets.describe()

           كنافة     بسبوسة     زلابيا     بقلاوة    ام علي
count   5.000000   5.000000   5.000000   5.000000  5.000000
mean   15.600000  19.800000   6.600000  16.000000  5.200000
std     5.770615   4.969909   2.302173   6.123724  2.588436
min     9.000000  14.000000   4.000000  10.000000  2.000000
25%    12.000000  15.000000   5.000000  11.000000  3.000000
50%    14.000000  22.000000   7.000000  14.000000  6.000000
75%    20.000000  23.000000   7.000000  22.000000  7.000000
max    23.000000  25.000000  10.000000  23.000000  8.000000

In [29]:
# ensure every column has five values to match the five‑entry index
x = pd.DataFrame({
                "كنافة": np.array([100,12,9,20,23]),
                "بسبوسة": np.array([150,14,23,25,22]),  # added fifth value
                "زلابيا": np.array([400,7,10,5,7]),
                "بقلاوة": np.array([100,14,11,22,23]),
                "ام علي": np.array([200,3,4,5,6])
                },
                index=["total","day1","day2","day3","day4"]
               )

x

       كنافة  بسبوسة  زلابيا  بقلاوة  ام علي
total    100     150     400     100     200
day1      12      14       7      14       3
day2       9      23      10      11       4
day3      20      25       5      22       5
day4      23      22       7      23       6

In [30]:
m=pd.DataFrame(x.loc["total"] - (x.loc["day1"] + x.loc["day2"] + x.loc["day3"] + x.loc["day4"]),columns=["المتبقي"])
m

        المتبقي
كنافة        36
بسبوسة       66
زلابيا      371
بقلاوة       30
ام علي      182