In [1]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np


df = pd.read_csv(
    "e_commerce.csv",
    dtype={
        "order_id": np.int16,
        "quantity": np.int8,
        "shipping_days": np.int8,
    },
    true_values=['Yes'],
    false_values=['No'],
    index_col=0,
)
df['order_date'] = pd.to_datetime(df['order_date'])
df.head()

,customer_id,order_date,product_category,product_name,quantity,unit_price,discount_pct,payment_method,country,city,shipping_days,customer_segment,return_status
order_id,,,,,,,,,,,,,
1001,CU-201,2020-01-15,Electronics,Wireless Headphones,1,89.99,0.05,Credit Card,USA,New York,3,Premium,False
1002,CU-156,2020-01-16,Clothing,Men's Jeans,2,45.50,0.15,PayPal,UK,London,5,Standard,True
1003,CU-342,2020-01-18,Home & Kitchen,Blender,1,32.75,0.00,Debit Card,Canada,Toronto,7,Standard,False
1004,CU-201,2020-02-02,Electronics,Smartphone,1,699.00,0.10,Credit Card,USA,New York,2,Premium,False
1005,CU-499,2020-02-05,Books,Python Programming,3,24.99,0.20,PayPal,Australia,Sydney,10,Budget,False

In [2]:
unit_price_after_discount = np.round(df['unit_price'] * (1 - df['discount_pct']), 2)

df.insert(7, "unit_price_after_discount", unit_price_after_discount)
df.insert(8, "total_price_after_discount", unit_price_after_discount * df['quantity'])
df.head()

,customer_id,order_date,product_category,product_name,quantity,unit_price,discount_pct,unit_price_after_discount,total_price_after_discount,payment_method,country,city,shipping_days,customer_segment,return_status
order_id,,,,,,,,,,,,,,,
1001,CU-201,2020-01-15,Electronics,Wireless Headphones,1,89.99,0.05,85.49,85.49,Credit Card,USA,New York,3,Premium,False
1002,CU-156,2020-01-16,Clothing,Men's Jeans,2,45.50,0.15,38.67,77.34,PayPal,UK,London,5,Standard,True
1003,CU-342,2020-01-18,Home & Kitchen,Blender,1,32.75,0.00,32.75,32.75,Debit Card,Canada,Toronto,7,Standard,False
1004,CU-201,2020-02-02,Electronics,Smartphone,1,699.00,0.10,629.10,629.10,Credit Card,USA,New York,2,Premium,False
1005,CU-499,2020-02-05,Books,Python Programming,3,24.99,0.20,19.99,59.97,PayPal,Australia,Sydney,10,Budget,False

In [3]:
pd.DataFrame(df[df["product_name"]== df["product_name"]].groupby(["product_name"])["shipping_days"].sum().sort_values(ascending=False).head(10))

                          shipping_days
product_name
Blender                              14
Mixer                                12
Kids' T-shirt                        12
Tablet                               11
Algorithms                           10
Statistics for Beginners             10
Python Programming                   10
Women's Sweater                       9
Air Fryer                             9
AI Fundamentals                       9

In [4]:
pd.DataFrame(df[df["country"]== df["country"]].groupby(["country"])["quantity"].sum().sort_values(ascending=False).head(10))

           quantity
country
USA              25
Canada           12
Germany          11
UK               11
Australia         6
France            2

In [5]:
x=df[["unit_price","discount_pct","quantity","shipping_days"]]
y=df["return_status"]
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=42)
model_1=LogisticRegression()
model_1.fit(x_train,y_train)
f"score:{model_1.score(x_test,y_test)*100:.2f}%"

'score:90.00%'

In [7]:
prediction_1 = model_1.predict(x_test)
result=pd.DataFrame({"unit_price": x_test["unit_price"],"discount_pct":x_test["discount_pct"],"quantity":x_test["quantity"],"shipping_days":x_test["shipping_days"],"return_status":y_test, "Predicted_return_status": prediction_1})
result.head()

,unit_price,discount_pct,quantity,shipping_days,return_status,Predicted_return_status
order_id,,,,,,
1014,29.99,0.20,1,9,False,False
1040,120.00,0.15,1,5,False,False
1031,499.99,0.05,1,3,False,False
1046,29.99,0.20,1,10,False,False
1018,34.99,0.15,2,8,False,False

In [ ]:
prediction_1=model_1.predict([[30,0.5,3,2]])
f"Predicted return status for unit price 30, discount percentage 0.5, quantity 3 and shipping days 2: {prediction_1}"

c:\Users\Cairo Lap\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

'Predicted return status for unit price 30, discount percentage 0.5, quantity 3 and shipping days 2: [False]'